import Head from 'next/head'
import Profile from '../components/profile'
import Nav from '../components/nav'
import axios from 'axios'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const dataP = await fetch('http://auth.alternativasistemas.com.br:8001/api/product')
  const dataC = await fetch('http://auth.alternativasistemas.com.br:8001/api/category')
  const product = await dataP.json()
  const category = await dataC.json()
  return {
      props: { product, category},
}
}
export default function Consult({ product, category }) {

  return (
    <>
        <div className={styles.container}>
      <Head>
          <title>Cadastro Produtos</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"></link>
        </Head>
        <Nav />
        <Profile />
        <main className={styles.main}>
        <p className={styles.title2}>CONSULTE ITENS</p>
        <div className='row'>
          <div className='col-md-6'>
            <div className={styles.cadastro}>
              <label>Consultar Produtos</label>
              <select className='form-select' id="consultaProdutos">
                <option selected>Selecione</option>
                {product?.map((item) => (
                  <option key={item.id}>{item.name}</option>
                ))}
              </select>
            </div>
          </div>
          <div className='col-md-6'>
            <div className={styles.cadastro}>
              <label>Consultar Categorias</label>
              <select className='form-select' id="consultaCategoria">
                <option selected>Selecione</option>
                {category?.map((item) => (
                  <option key={item.id}>{item.name}</option>
                ))}
              </select>
            </div>
          </div>
        </div>
        </main>
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </>
  )
}
