import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Profile from '../components/profile'
import Nav from '../components/nav'


export default function Excluir() {
    return (

      <div className={styles.container}>
        <Head>
          <title>Cadastro Produtos</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"></link>
        </Head>
        <Nav />
        <Profile />
        <main className={styles.main}>
        <div className='container'>
            <p className={styles.title2}>DELETAR Produtos/Categorias</p>
            <div className='row'>
            <div className='col-md-6'>
                <div className={styles.cadastro}>
                    <label>Escolha o Produto</label>
                    <select className='form-select' id="consultaProdutos">
                        <option value={''}>Select</option>
                    </select>
                </div>
            </div>
            <div className='col-md-6'>
                <div className={styles.cadastro}>
                    <label>Escolha a Categoria</label>
                    <select className='form-select' id="consultaCategoria">
                        <option value={''}>Select</option>
                    </select>
                </div>
            </div>

            </div>
        </div>
        </main>
        <script src="main.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      </div>
    
    )
   
}
