import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Profile from '../components/profile'
import Nav from '../components/nav'
import axios from 'axios'
import {useForm} from 'react-hook-form'
import {yupResolver} from '@hookform/resolvers/yup'
import * as yup from "yup";

const urlProduto = "http://auth.alternativasistemas.com.br:8001/api/product"
const urlCategoria = "http://auth.alternativasistemas.com.br:8001/api/category"


export default function Incluir() {
    
const { register, handleSubmit, formState:{ error}} = useForm({
    resolver: yupResolver(validationPost)
})

  const addPost = data => axios.post('http://auth.alternativasistemas.com.br:8001/api/product', data)
  .then(()=>{
   alert('Produto Cadastrado!')
  })
  .catch(()=>{
    console.log('erro de post')
  })

    return (

      <div className={styles.container}>
        <Head>
          <title>Cadastro Produtos</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"></link>
        </Head>
        <Nav />
        <Profile />
        <main className={styles.main}>
        <div className='container'>
            <p className={styles.title2}>ADICIONE ITENS</p>
            <div className='row'>
                <div className='col-md-6'>
                    <details className={styles.itens}>
                        <summary>Incluir Produto</summary>
                        <p>
                            <label>Informe o nome do produto</label>
                            <input className='form-control' id='nameIncluir' type={'text'}></input>
                            <label>Informe a descrição</label>
                            <textarea className='form-control' id='descricaoIncluir' placeholder='Informe a Descrição'></textarea>
                            <label>Informe o valor R$</label>
                            <input className='form-control' id='valorIncluir' type={'number'}></input>
                            <label>Escolha a Categoria</label>
                            <select className='form-select' id="consultaCategoria">
                                <option value={''}>Select</option>
                            </select>
                            <button className='btnP' onClick={addNewP}>Incluir</button>
                        </p>
                    </details>

                </div>
                <div className='col-md-6'>
                    <details className={styles.itens}>
                        <summary>Incluir Categoria</summary>
                        <p>
                            <label>Informe o nome da categoria</label>
                            <input className='form-control' type={'text'}></input>
                            <label>Informe a descrição</label>
                            <textarea className='form-control' placeholder='Informe a Descrição'></textarea>
                            <button className='btnP' type='submit'>Incluir</button>
                        </p>
                    </details>
                </div>
            </div>
        </div>
        </main>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      </div>
    
    )
   
}
