import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Profile from '../components/profile'
import Nav from '../components/nav'
import axios from 'axios'
import { useState } from 'react'

export default function Incluir() {

    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Cadastro Produtos</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"></link>
                </Head>
                <Nav />
                <Profile />
                <main className={styles.main}>
                    <div className='container'>
                        <p className={styles.title2}>ADICIONE ITENS</p>
                        <div className='row'>
                            <div className='col-md-6'>
                                <details className={styles.itens}>
                                    <summary>Incluir Produto</summary>
                                        <form>
                                            <label>Informe o nome do produto</label>
                                            <input className='form-control' name='name' id='name' type={'text'}></input>
                                            <label>Informe a descrição</label>
                                            <textarea className='form-control' name='description' id='description' placeholder='Informe a Descrição'></textarea>
                                            <label>Informe o valor R$</label>
                                            <input className='form-control' name='value' id='value' type={'number'}></input>
                                            <button type='submit' className='btnP'>Incluir</button>
                                        </form>
                                </details>

                            </div>

                            <div className='col-md-6'>
                                <details className={styles.itens}>
                                    <summary>Incluir Categoria</summary>
                                        <label>Informe o nome da categoria</label>
                                        <input className='form-control' type={'text'}></input>
                                        <label>Informe a descrição</label>
                                        <textarea className='form-control' placeholder='Informe a Descrição'></textarea>
                                        <button className='btnP' type='submit'>Incluir</button>
                                </details>
                            </div>
                        </div>
                    </div>
                </main>
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
            </div>
        </>

    )

}
